[package]
name = "xtask"
version = "0.1.0"
edition = "2024"

[dependencies]
allocator-api2 = { workspace = true }
clap = { version = "4.5", features = ["derive"] }
engine = { path = "../engine" }

[lints]
workspace = true
